server:
  port: 8080

spring:
  application:
    name: prueba-tecnica-sysman-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate.ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt:
  secret:
    key: 9f99a1aae8ff512c319f04cebfa172693816c3203b68f7e3d1bae52167eda05c
  expiration: 3600000
  issuer: prueba_tecnica_sysman_backend

